version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "8080:80"
    env_file:
      - ./client/.env  

  backend:
    build: ./server
    ports:
      - "5000:50"
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
